// <auto-generated />
namespace ResumeBuilder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedrolefieldinusermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedrolefieldinusermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202003111035225_added role field in user model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
