// <auto-generated />
namespace ResumeBuilder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class renameroletouserroleinusersmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renameroletouserroleinusersmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202003130856098_rename role to user role in users model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
