// <auto-generated />
namespace ResumeBuilder.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedCoursemodelandcourseidpropertiesineducationaldetails : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedCoursemodelandcourseidpropertiesineducationaldetails));
        
        string IMigrationMetadata.Id
        {
            get { return "202003110722076_Added Course model and courseid properties in educationaldetails"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
